[package]
name = "ascii_raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.windows]
windows = "0.41.0"
features = [
    "Win32_UI_Input_KeyboardAndMouse",
]